function footer(){
document.write ('<div id="lixil-lineup">');
document.write ('<h2><span><a href="http://www.lixil.co.jp/products/">LIXIL（リクシル）の商品ラインアップ</a></span></h2>');
document.write ('<p id="btnAllTop"><a href="http://www.lixil.co.jp/">総合トップへ</a></p>');
document.write ('<div class="lixil-lineup-inner">');
document.write ('<div class="firstArea">');
document.write ('<h3><a href="http://www.lixil.co.jp/products/door_window/">玄関ドア・引戸/窓</a></h3>');
document.write ('<ul>');
document.write ('<li>玄関ドア・引戸</li>');
document.write ('<li>窓</li>');
document.write ('<li>シャッター・面格子</li>');
document.write ('<li>勝手口ドア・引戸</li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<div class="secondArea">');
document.write ('<h3><a href="http://www.lixil.co.jp/products/kitchen_bathroom/">キッチン・浴室・洗面化粧室・トイレ</a></h3>');
document.write ('<ul>');
document.write ('<li>システムキッチン</li>');
document.write ('<li>浴室</li>');
document.write ('<li>洗面化粧室</li>');
document.write ('<li>トイレ</li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<div class="thirdArea">');
document.write ('<h3><a href="http://www.lixil.co.jp/products/interior/">インテリア建材</a></h3>');
document.write ('<ul>');
document.write ('<li>室内ドア・引戸</li>');
document.write ('<li>収納</li>');
document.write ('<li>床・階段・手すり</li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<div class="endArea">');
document.write ('<h3><a href="http://www.lixil.co.jp/products/exterior/">エクステリア</a></h3>');
document.write ('<ul>');
document.write ('<li>門扉</li>');
document.write ('<li>フェンス</li>');
document.write ('<li>車庫・カーポート</li>');
document.write ('<li>庭</li>');
document.write ('<li>バルコニー</li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<div class="clear"></div>');
document.write ('</div>');
document.write ('<div class="lixil-lineup-inner lastBox">');
document.write ('<div class="firstArea">');
document.write ('<h3><a href="http://www.lixil.co.jp/products/roof_outerwall/">屋根・外壁材</a></h3>');
document.write ('<ul>');
document.write ('<li>屋根材</li>');
document.write ('<li>外壁材</li>');
document.write ('<li>外装タイル</li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<div class="secondArea">');
document.write ('<h3><a href="http://www.lixil.co.jp/products/structure/">高性能住宅工法</a></h3>');
document.write ('<ul>');
document.write ('<li>高気密・高断熱・高耐震住宅工法</li>');
document.write ('<li>耐震補償付き構造体</li>');
document.write ('<li>高断熱パネル</li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<div class="thirdArea">');
document.write ('<h3><a href="http://www.lixil.co.jp/products/building_equipment/">ビル・店舗用建材/厨房設備</a></h3>');
document.write ('<ul>');
document.write ('<li>カーテンウォール</li>');
document.write ('<li>玄関ドア・窓・シャッター</li>');
document.write ('<li>業務用厨房機器</li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<div class="endArea">');
document.write ('<h3><a href="http://www.lixil.co.jp/products/public/">公共向けエクステリア・トイレ</a></h3>');
document.write ('<ul>');
document.write ('<li>大型門扉</li>');
document.write ('<li>大型フェンス</li>');
document.write ('<li>駐車場</li>');
document.write ('<li>手すり</li>');
document.write ('<li>トイレ</li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<div class="clear"></div>');
document.write ('</div>');
document.write ('</div>');
document.write ('<hr />');
document.write ('<div id="footer">');
document.write ('<h2 class="anchor"><a name="anchorFooter" id="anchorFooter">サイト情報</a></h2>');
document.write ('<div class="footer_link">');
document.write ('<ul>');
document.write ('<li><a href="http://www.lixil.co.jp/termsofuse/" target="_blank"><img src="/cmn/images/footer_btn_caution.gif" alt="サイトのご利用について" width="119" height="14" class="rollover" /></a><img src="/cmn/images/footer_line.gif" alt="" /></li>');
document.write ('<li><a href="http://www.lixil.co.jp/privacy/" target="_blank"><img src="/cmn/images/footer_btn_privacy.gif" alt="プライバシーポリシー" width="106" height="14" class="rollover" /></a></li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<div class="footer_copyright"><img src="/cmn/images/footer_copyright.gif" width="237" height="14" alt="Copyright (c) LIXIL Corporation. All rights reserved." align="absmiddle" />&nbsp;&nbsp;<a href="http://www.jsgc.co.jp/" target="_top"><img src="/cmn/images/footer_lixil.gif" width="112" height="22" alt="LIXILグループ" align="absmiddle" border="0" /></a></div>');
document.write ('<!--footer-->');
document.write ('</div>');
document.write ('<script type="text/javascript">');
document.write ('<!--');
document.write ('jQuery.noConflict();');
document.write ('//-->');
document.write ('</script>');
document.write ('<script src="//c.marsflag.com/mf/mfx/1.0/js/mfx-sbox.js" charset="UTF-8"></script>');
}