function header(){
document.write ('<div id="header">');
document.write ('<div class="atlwrap">');
document.write ('<p id="tagline"><a class="tagline-left" href="http://www.lixil.co.jp/"><img src="/cmn/images/header_tagline_logo.gif" alt="株式会社LIXIL" width="129" height="29" /></a><a class="tagline-right" href="http://www.lixil.co.jp/"><img src="/cmn/images/header_tagline_lixil.gif" alt="LIXIL" width="70" height="29" /></a></p>');
document.write ('<p class="logo"><a href="/index.html" target="_top"><img src="/cmn/images/header_logo.gif" alt="SHINNIKEI　新日軽" width="114" height="53" class="atl"/></a></p>');
document.write ('<div id="headerSkip">');
document.write ('<p>ページ内を移動するためのリンクです。</p>');
document.write ('<ul>');
document.write ('<li><a href="#anchorGlobalnavigation">グローバルナビゲーションへ</a></li>');
document.write ('<li><a href="#anchorContents">本文へ</a></li>');
document.write ('<li><a href="#anchorLocalnavigation">ローカルナビゲーションへ</a></li>');
document.write ('<li><a href="#anchorFooter">サイト情報へ</a></li>');
document.write ('</ul>');
document.write ('</div>');
document.write ('<hr />');
document.write ('<div id="header-right-box">');
document.write ('<div id="header-option">');
document.write ('<ul>');
document.write ('<li><a href="/sitemap.htm" target="_top"><img src="/cmn/images/header_btn_sitemap.gif" alt="サイトマップ" width="70" height="23" class="rollover" /></a></li>');
document.write ('<li id="header-show"><a href="http://www.lixil.co.jp/showroom/"><img src="/cmn/images/header_btn_showroom.gif" alt="ショールーム" width="94" height="24" class="rollover" /></a></li>');
document.write ('<li><a href="/pro/index.html" target="_top"><img src="/cmn/images/header_btn_pro.gif" alt="ビジネスユーザー向け" width="138" height="23" class="rollover" /></a></li>');
document.write ('</ul>');
document.write ('<div id="search-area">');
document.write ('<link href="//c.marsflag.com/mf/mfx/1.0/css/mfx-sbox.css" type="text/css" rel="stylesheet" />');
document.write ('<div class="mf_finder_container">');
document.write ('<mf-search-box submit-text="検索" placeholder="サイト内検索" ajax-url="//mf2ap081.marsflag.com/lixil__all__customelement/x_search.x" serp-url="//www.lixil.co.jp/search.htm#/" doctype-hidden options-hidden></mf-search-box>');
document.write ('</div>');
document.write ('<!--search-area-->');
document.write ('</div>');
document.write ('<!--header-option-->');
document.write ('</div>');
document.write ('<!--header-right-box-->');
document.write ('</div>');
document.write ('<!--atlwrap-->');
document.write ('</div>');
document.write ('<!--header-->');
document.write ('</div>');
document.write ('<hr />');
document.write ('<div id="gNav">');
document.write ('<ul>');
document.write ('<li><a href="/index.html" class="home">HOME</a></li>');
document.write ('<li><a href="/products/index.html" class="products" target="_top">商品情報</a></li>');
document.write ('<li><a href="/sumai/index.html" class="sumai" target="_top">住まいづくり情報</a></li>');
document.write ('<li><a href="/catalog/index.html" class="catalog" target="_top">カタログ</a></li>');
document.write ('<li><a href="/inquery/index.html" class="inquery" target="_top">お客様サポート</a></li>');
document.write ('<li><a href="/company/index.html" class="company" target="_top">新日経について</a></li>');
document.write ('</ul>');
document.write ('<!--global-navi-->');
document.write ('</div>');
}